### ISSUE TITLE
Compilation error with scala 2.13.2

### ISSUE THREAD

**Issue by yanns** [scalate/scalate#262]
With scala 2.13.2, I have the following error:
```
Caused by: java.lang.NoSuchMethodError: scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(Ljava/lang/String;)V
	at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:144)
	at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:50)
	at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:37)
	at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:233)
	at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:223)
	at org.fusesource.scalate.TemplateEngine.compiler(TemplateEngine.scala:223)
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:788)
	... 102 common frames omitted
```

**Comment by magnolia-k** [comment]
Probably due to the incompatibility of Scala 2.13.1 -> 2.13.2, since Scalate itself can compile with 2.13.2, which should be resolved once it's released.

**Comment by pjfanning** [comment]
I have a demo that illustrates this - https://github.com/pjfanning/scalate-sample/tree/scala-2.13

**Comment by magnolia-k** [comment]
Scalate 1.5.6 has been released.
It is Scala 2.13.2 compliant.

**Comment by yanns** [comment]
You mean [1.9.6](https://github.com/scalate/scalate/compare/scalate-project-1.9.5...scalate-project-1.9.6)?
thx a lot!! ❤️

**Comment by magnolia-k** [comment]
Oops, I misspelled the version number... I'm talking about 1.9.6.
