### ISSUE TITLE
Please release a new version for Scala 2.12.13

### ISSUE THREAD

**Issue by ngocdaothanh** [scalate/scalate#309]
**Is your feature request related to a problem? Please describe.**

Running scalate-core 1.9.6 with Scala 2.13.4 or 2.12.12 is OK.

But when running with Scala 2.12.13 (released a few days ago, on [12 JANUARY 2021](https://www.scala-lang.org/news/2.12.13)), there's this error:

```
Caused by: org.fusesource.scalate.TemplateException: scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(Ljava/lang/String;)V
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:864)
	at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:725)
	at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:436)
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:430)
	at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:649)
	at xitrum.view.ScalateEngineRenderString.renderString(ScalateEngineRenderString.scala:50)
	... 23 common frames omitted
Caused by: java.lang.NoSuchMethodError: scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(Ljava/lang/String;)V
	at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:132)
	at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:50)
	at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:37)
	at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:232)
	at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:222)
	at org.fusesource.scalate.TemplateEngine.compiler(TemplateEngine.scala:222)
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:787)
	... 28 common frames omitted
```

Source code in scala-compiler-2.12.12-sources.jar:

```
  class OutputSetting private[nsc](
    private[nsc] val outputDirs: OutputDirs,
    default: String)
    extends StringSetting("-d", "directory|jar", "destination for generated classfiles.", default, None) {
      value = default
      override def value_=(str: String) {
        super.value_=(str)
        try outputDirs.setSingleOutput(str)
        catch { case FatalError(msg) => errorFn(msg) }
      }
  }
```

In Scala 2.12.13, the code is different:

```
    def value_=(arg: T) = {
      setByUser = true
      v = arg
      postSetHook()
    }
```

**Describe the solution you'd like**

Please recompile Scalate with Scala 2.12.13 and release a new version.

**Describe alternatives you've considered**

It's not ideal, but I think an alternative solution is using JAR shading to create a fat Scalate JAR which embeds a version of Scala 2.12.x compiler.

**Comment by anilkumarmyla** [comment]
We ran into the same after we upgraded sbt to 1.5.0 which seems to switche to using 2.12.13. Any help needed here? I see that https://github.com/scalate/scalate/pull/326 is closed, any reason?

**Comment by zzvara** [comment]
With SBT `1.5.1` and `sbt-scoverage` 1.7.0, Scala `2.12.13`, 59 out of 767 of our tests fail:

```
29-Apr-2021 13:45:44	2021-04-29 13:45:44.339 ERROR [t-dispatcher-20] i.AbstractSupervisor: Supervisor RestartSupervisor saw failure: 'void scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(java.lang.String)'
29-Apr-2021 13:45:44	java.lang.NoSuchMethodError: 'void scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(java.lang.String)'
29-Apr-2021 13:45:44	        at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:132) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:50) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:37) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:232) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:222) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
``` 

We use `org.fusesource.scalate.TemplateEngine` to generate e-mail templates, that is, `scalate-core_2.12-1.9.6`.

Thanks!

**Comment by zzvara** [comment]
I released a new version `1.9.7` available from:

`"Enliven Systems Central".at(s"https://central.enliven.systems/artifactory/sbt-release/")`

Or build your own: https://github.com/zzvara/scalate

It allows you to upgrade to:
SBT 1.5.1
Scala 2.12.13
Scoverage 1.7.0

Temporarily it may suffice.

**Comment by anilkumarmyla** [comment]
@zzvara Thanks for the help, why not submit your changes as a PR to this repo?

**Comment by zzvara** [comment]
@anilkumarmyla As you can see on the attached repository and commits, it is pretty easy to fix the problems for Scala version 2.12.13.

Figuring out why tests fail around class names, fixing them, patching the build (which is quite complex) to still support users below 2.12.13 (2.12.X), and figuring out the versioning is the hard part I think I'm not qualified to do.
