### ISSUE TITLE
Binary compatibility problem with 2.13.1?

### ISSUE THREAD

**Issue by DWvanGeest** [scalate/scalate#238]
Hi, thanks for your work on this project!

When trying to compile a template under Scala 2.13.1 and scalate-core 1.9.4, I hit this error:

```
[info]   org.fusesource.scalate.TemplateException: scala.tools.nsc.Settings.deprecation()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
[info]   at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:865)
[info]   at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:726)
[info]   at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:437)
[info]   at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:431)
[info]   at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:486)
[info]   at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:583)
<omitted>
[info]   ...
[info]   Cause: java.lang.NoSuchMethodError: scala.tools.nsc.Settings.deprecation()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
[info]   at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:147)
[info]   at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:50)
[info]   at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:37)
[info]   at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:233)
[info]   at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:223)
[info]   at org.fusesource.scalate.TemplateEngine.compiler(TemplateEngine.scala:223)
[info]   at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:788)
[info]   at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:726)
[info]   at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:437)
[info]   at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:431)
```

Note that the same code and template works fine on 2.13.0.

I have in place the normal workaround for these issues:

```
    dependencyOverrides := Seq( // necessary to avoid conflicts which mess up scalate
      "org.scala-lang" % "scala-library" % scalaVersion.value,
      "org.scala-lang" % "scala-reflect" % scalaVersion.value,
      "org.scala-lang" % "scala-compiler" % scalaVersion.value
    )
```

Any idea what could be wrong?

**Comment by xuwei-k** [comment]
https://github.com/scalate/scalate/releases/tag/scalate-project-1.9.5 
1.9.5 released

**Comment by seratch** [comment]
We believe this issue has been fixed in version 1.9.5.
