### PR TITLE
Compile with scala 2.12.13

### LINKED ISSUE #309: Please release a new version for Scala 2.12.13
**Is your feature request related to a problem? Please describe.**

Running scalate-core 1.9.6 with Scala 2.13.4 or 2.12.12 is OK.

But when running with Scala 2.12.13 (released a few days ago, on [12 JANUARY 2021](https://www.scala-lang.org/news/2.12.13)), there's this error:

```
Caused by: org.fusesource.scalate.TemplateException: scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(Ljava/lang/String;)V
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:864)
	at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:725)
	at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:436)
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:430)
	at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:649)
	at xitrum.view.ScalateEngineRenderString.renderString(ScalateEngineRenderString.scala:50)
	... 23 common frames omitted
Caused by: java.lang.NoSuchMethodError: scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(Ljava/lang/String;)V
	at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:132)
	at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:50)
	at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:37)
	at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:232)
	at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:222)
	at org.fusesource.scalate.TemplateEngine.compiler(TemplateEngine.scala:222)
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:787)
	... 28 common frames omitted
```

Source code in scala-compiler-2.12.12-sources.jar:

```
  class OutputSetting private[nsc](
    private[nsc] val outputDirs: OutputDirs,
    default: String)
    extends StringSetting("-d", "directory|jar", "destination for generated classfiles.", default, None) {
      value = default
      override def value_=(str: String) {
        super.value_=(str)
        try outputDirs.setSingleOutput(str)
        catch { case FatalError(msg) => errorFn(msg) }
      }
  }
```

In Scala 2.12.13, the code is different:

```
    def value_=(arg: T) = {
      setByUser = true
      v = arg
      postSetHook()
    }
```

**Describe the solution you'd like**

Please recompile Scalate with Scala 2.12.13 and release a new version.

**Describe alternatives you've considered**

It's not ideal, but I think an alternative solution is using JAR shading to create a fat Scalate JAR which embeds a version of Scala 2.12.x compiler.

### PR DESCRIPTION
**Pull request by anilkumarmyla**
Fixes #309 

It appears that ScalaCompiler.scala changes for 2.13+ started working for 2.12.13+, so did the following moves to get the project working for all scala cross versions

Copy 2.13- ScalaCompiler.scala to 2.11
Copy 2.13+ ScalaCompiler.scala to 2.12
Move 2.13+ to 2.13 and get rid of 2.13+ unmanaged source directory

Also mark the tests failing for 2.13 to 2.12 😞

### CODE REVIEW

**Comment by anilkumarmyla** [comment]
Not sure how to fix the mima failure 🤔

**Comment by anilkumarmyla** [comment]
@xuwei-k Any pointers on how to resolve the mima failure?

**Review by magnolia-k — APPROVED** [review]

**Comment by magnolia-k** [comment]
@anilkumarmyla 

Sorry for the late comment.
I updated the Mima plugin, and following the error message,
I specified an out-of-scope method, and now the compilation passes!
